// "use client"

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from '@/components/navbar'
import { LayoutWrapper } from "@/components/layout-wrapper";
import { UserProvider } from "@/context/userContext";
import ReactQueryProvider from "@/utils/providers/queryProvider";
import { Suspense } from "react";
import Loading from "./loading";
import { GlobalLoader } from "@/components/ui/global-loader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <LayoutWrapper>
        <Suspense fallback={<Loading />}>
          <ReactQueryProvider>
            <UserProvider>
              <GlobalLoader />
              {children}
            </UserProvider>
          </ReactQueryProvider>
        </Suspense>
      </LayoutWrapper>
    </body>
    </html>
  );
}
