"use client"

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from '@/components/navbar'
import { CartProvider } from "@/context/CartContext";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const pathname = usePathname();

  const hideLayout = pathname === "/login" || pathname === "/signup";

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {!hideLayout && <Navbar />}

        <main className="px-10 py-10">
          {children}
        </main>

        {!hideLayout &&
          <footer className="flex py-4 px-20 justify-center items-center opacity-80">
            Created as a part of a bigger project Nazar with ❤️ by Sanika
          </footer>}
      </body>
    </html>
  );
}
